### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by Superman-Valencia** [vigor-jzhang/icc-regularizer#1]
Hello author, thank you very much for your great work in the paper. When studying your public code, I have some questions:
(1) In ICCRegularizer.py, "sample" in Need embeddings shape [class #, samples #, emb dim] does mean the size of batch?
(2) Is the embedding feature a two-dimensional feature or a one-dimensional feature? what does class mean?

If I have embeddings with the shape of [batch, emd_dim] as input,  is it right? 
Does the code also apply to the input embedding with the shape[batch, t, dim]?

Looking forward to your reply, thank you very much！🙇‍

**Comment by vigor-jzhang** [comment]
Sorry for the late reply. Here is an example:

For one batch of data, assuming you have 6 speakers (i.e., 6 classes), 8 audio files for each speaker (i.e., 8 samples), and 256 dimension embeddings for each file (i.e., 256 emb-dim).

Then, for one batch of data, you should input a shape of [6, 8, 256] tensor to this regularizer.

For your question:

[batch, emb_dim] - this is not workable. If using the previous example, what you input actually is [6*8, 256]. ICC regularizer cannot handle it.

[batch, t, dim] - This has the same shape as my example. If here the 't' means different views/samples/files/etc. from the same batch #, then it is applicable.

I have updated the repository with an example code, you can check it.

**Comment by Superman-Valencia** [comment]
> Sorry for the late reply. Here is an example:
> 
> For one batch of data, assuming you have 6 speakers (i.e., 6 classes), 8 audio files for each speaker (i.e., 8 samples), and 256 dimension embeddings for each file (i.e., 256 emb-dim).
> 
> Then, for one batch of data, you should input a shape of [6, 8, 256] tensor to this regularizer.
> 
> For your question:
> 
> [batch, emb_dim] - this is not workable. If using the previous example, what you input actually is [6*8, 256]. ICC regularizer cannot handle it.
> 
> [batch, t, dim] - This has the same shape as my example. If here the 't' means different views/samples/files/etc. from the same batch #, then it is applicable.
> 
> I have updated the repository with an example code, you can check it.

Thank you for your reply.😊
